In [9]:
#
# Chapter 7, Example 1
#

import tensorflow as tf
import numpy as np
from tensorflow.keras import Model, layers, models

# Check the version of Tensorflow (2.2.0)
print(tf.__version__)

2.2.0


In [10]:
# Input image
I = np.array([[0.5, -0.1, 0.2, 0.3, 0.5],
              [0.8, 0.1, -0.5, 0.5, 0.1],
              [-1.0, 0.2, 0.0, 0.3, -0.2],
              [0.7, 0.1, 0.2, -0.6, 0.3],
              [-0.4, 0.0, 0.2, 0.3, -0.3]]).astype(np.float32)
print(I)

[[ 0.5 -0.1  0.2  0.3  0.5]
 [ 0.8  0.1 -0.5  0.5  0.1]
 [-1.   0.2  0.   0.3 -0.2]
 [ 0.7  0.1  0.2 -0.6  0.3]
 [-0.4  0.   0.2  0.3 -0.3]]


In [11]:
# Model definition
class MyModel(Model):
    def __init__(self, pad):
        super(MyModel, self).__init__()
        self.seq = models.Sequential()
        self.seq.add(layers.Conv2D(1, 3, strides=(1,1), padding=pad, input_shape=[5,5,1]))

    def call(self, x):
        u = self.seq(x)
        y = tf.nn.sigmoid(u)
        return u,y


In [12]:
# Set filters and bias
w = np.array([[0, 1, 1],[1, 0, 1], [1, 1, 0]]).astype(np.float32).reshape(3,3,1,1)
b = np.array([0.05]).astype(np.float32)

In [13]:
# VALID padding for convolution
model = MyModel('VALID')
# SAME padding for convolution
# model = MyModel('same'')

model.seq.summary() 
model.seq.set_weights([w,b])
# filters
print(model.seq.weights[0])
# bias
print(model.seq.weights[1])


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 3, 3, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
<tf.Variable 'conv2d_1/kernel:0' shape=(3, 3, 1, 1) dtype=float32, numpy=
array([[[[0.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[0.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[0.]]]], dtype=float32)>
<tf.Variable 'conv2d_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.05], dtype=float32)>


In [14]:
# evaluate u and y
u, y = model(I.reshape([1, 5, 5, 1]))
print('VALID padding for convolution\n')
print('u: %s\n'%np.array(u).reshape([3, 3]))
print('y: %s\n'%np.array(y).reshape([3, 3]))

VALID padding for convolution

u: [[-0.34999996  1.35        0.75000006]
 [-0.54999995  0.85        0.05      ]
 [ 0.75000006  0.04999999  1.15      ]]

y: [[0.41338244 0.7941296  0.6791787 ]
 [0.36586443 0.7005672  0.5124974 ]
 [0.6791787  0.5124974  0.7595109 ]]



In [15]:
# evaluate o for VALID
o = tf.nn.max_pool(y, ksize=[1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'VALID')
print('VALID padding for pooling')
print('o: %s'%np.array(o).reshape([1, 1]))

VALID padding for pooling
o: [[0.7941296]]


In [16]:
# evaluate o for SAME
o = tf.nn.max_pool(y, ksize=[1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'SAME')
print('SAME padding for pooling')
print('o: %s'%np.array(o).reshape([2, 2]))

SAME padding for pooling
o: [[0.7941296 0.6791787]
 [0.6791787 0.7595109]]
